dist: trusty
sudo: true
language: cpp
cache: ccache

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main'
    packages:
      - libboost-all-dev
      - libglew-dev
      - libfreetype6-dev

before_install:
    - sudo apt-get --allow-unauthenticated install libglfw3-dev
      
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
