dist: trusty
sudo: false
language: cpp

addons:
  apt:
    packages:
      - libboost-all-dev
      - libglew-dev
      - libglfw3-dev
      - libfreetype6-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
