# g++7 see: https://github.com/richelbilderbeek/travis_gcc_cpp17/blob/master/.travis.yml
# boost see: https://stackoverflow.com/questions/45276457/how-to-use-latest-boost-version-in-travis-ci

dist: trusty
sudo: true
language: cpp
cache: ccache

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main'
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - boost1.67
      - libglew-dev
      - libglm-dev
      - libfreetype6-dev
      - xorg-dev # needed by glfw3
      - libglu1-mesa-dev # needed by glfw3

env:
  COMPILER=g++-8
      
before_install:
  - sudo apt-get --allow-unauthenticated install libglfw3-dev

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
