dist: bionic
language: cpp
cache: ccache

addons:
  apt:
    update: true
    packages:
      - libboost-all-dev
      - libglfw3-dev
      - libglew-dev
      - libglm-dev
      - libfreetype6-dev
      - xorg-dev # needed by glfw3
      - libglu1-mesa-dev # needed by glfw3

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
