dist: bionic
language: cpp
cache: ccache

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - clang-9
      - clang-tidy-9
      - clang-format-9
      - g++-9
      - libboost-all-dev
      - libglfw3-dev
      - libglew-dev
      - libglm-dev
      - libfreetype6-dev
      - xorg-dev # needed by glfw3
      - libglu1-mesa-dev # needed by glfw3

compiler:
  - gcc
  - clang

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-9 100
  - sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-9 100
  - sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-9 100

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
